import React from 'react';
import { Scan, Activity, Eye, Cpu } from 'lucide-react';

export const MethodologySection: React.FC = () => {
  const steps = [
    {
      index: '01',
      title: 'Spatial Affine & Boundary Localization',
      description: 'Face-swapping architectures blend a generated facial mask onto a host target frame. The thermal heat map pinpoints sub-pixel color transitions, resolution disparities, and blur seams around the jawline, ears, and hairline.',
      icon: Scan
    },
    {
      index: '02',
      title: 'Discrete Cosine Transform (DCT) Residuals',
      description: 'Generative adversarial networks (GANs) and diffusion models generate pixel correlations that fail high-frequency Fourier decomposition. The model isolates unnatural spectral smoothing across dermal regions.',
      icon: Activity
    },
    {
      index: '03',
      title: 'Biological Signal & Cornea Vector Physics',
      description: 'Natural human faces exhibit remote photoplethysmography (rPPG) rhythmic micro-pulsing from cardiac blood volume flow and consistent specular pupil catchlights that match ambient room light sources.',
      icon: Eye
    },
    {
      index: '04',
      title: 'Audio-Visual Phonetic Synchronization',
      description: 'AI voice clones and lip dubbers fail temporal alignment on bilabial plosive phonemes (such as /p/, /b/, and /m/). Neural cross-attention flags audio packets preceding visual lip aperture.',
      icon: Cpu
    }
  ];

  return (
    <section id="methodology" className="py-12 border-t border-slate-800/80">
      <div className="mb-8">
        <div className="flex items-center gap-2 text-xs font-mono text-slate-400 mb-2">
          <span>FORENSIC PRINCIPLES</span>
          <span aria-hidden="true">·</span>
          <span>4-STAGE ENSEMBLE</span>
        </div>
        <h2 className="text-2xl font-bold text-slate-100 tracking-tight">
          How the Heat Map Identifies Manipulation
        </h2>
        <p className="text-sm text-slate-400 mt-1 max-w-2xl leading-relaxed">
          The heat map highlights localized anomaly tensors generated by convolutional feature maps, pointing directly to synthetic artifacts.
        </p>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-4">
        {steps.map((step) => {
          const Icon = step.icon;
          return (
            <div
              key={step.index}
              className="p-5 bg-slate-900/50 border border-slate-800/80 rounded-xl flex flex-col justify-between"
            >
              <div>
                <div className="flex items-center justify-between mb-4">
                  <span className="font-mono text-xs font-semibold text-rose-400">
                    {step.index}.
                  </span>
                  <div className="p-2 rounded-lg bg-slate-800/80 text-slate-300">
                    <Icon className="w-4 h-4 text-rose-400" />
                  </div>
                </div>

                <h3 className="text-sm font-semibold text-slate-200 mb-2">
                  {step.title}
                </h3>

                <p className="text-xs text-slate-400 leading-relaxed">
                  {step.description}
                </p>
              </div>
            </div>
          );
        })}
      </div>
    </section>
  );
};
